window.NSQUARE_PROJECTS = [
  {
    slug: "ravine-villa",
    name: "Ravine Villa",
    status: "ongoing",
    type: "villa residential",
    location: "Indiranagar, Bengaluru",
    area: "20,000 sq ft",
    client: "Ravine Villa",
    image: "Images/Elevation/Praveen Villa - Indiranagar.png",
    secondaryImage: "Images/wireframe.jpg",
    summary: "Independent villa shaped around layered terraces, greenery and warm residential detailing.",
    details: "A residential villa planned around generous setbacks, private terraces and a composed street-facing elevation. The design focuses on natural light, layered massing and a warm material palette suitable for a premium urban home.",
    scope: ["Architecture planning", "Elevation design", "Material direction", "Site coordination"]
  },
  {
    slug: "jaleel-complex",
    name: "Jaleel Complex",
    status: "ongoing",
    type: "commercial mixed-use",
    location: "RT Nagar, Bengaluru",
    area: "32,000 sq ft",
    client: "Jaleel Complex",
    image: "Images/Elevation/jaleel Complex RT Nagar.png",
    secondaryImage: "Images/jaleel Complex RT Nagar.png",
    summary: "Mixed-use complex with a retail base, classical frontage and efficient upper-floor planning.",
    details: "A mixed-use building combining active frontage with efficient upper-floor layouts. The elevation balances commercial visibility with a measured architectural language for a dense urban street.",
    scope: ["Mixed-use planning", "Commercial frontage", "Facade design", "Execution coordination"]
  },
  {
    slug: "guzdar-apartment",
    name: "Guzdar Apartment",
    status: "ongoing",
    type: "apartment residential",
    location: "Banaswadi, Bengaluru",
    area: "9,000 sq ft",
    client: "Guzdar Apartment",
    image: "Images/Elevation/Gulzar Apartment Bnaswadi.jpg",
    secondaryImage: "Images/Gulzar Apartment Bnaswadi.jpg",
    summary: "Residential apartment with a strong street presence and carefully proportioned balconies.",
    details: "A compact residential apartment project designed with clear facade rhythm, efficient planning and balcony proportions that create a stronger street presence.",
    scope: ["Apartment planning", "Elevation design", "Balcony detailing", "Approval coordination"]
  },
  {
    slug: "asif-apartment",
    name: "Asif Apartment",
    status: "ongoing",
    type: "apartment residential",
    location: "Fraser Town, Bengaluru",
    area: "8,000 sq ft",
    client: "Asif Apartment",
    image: "Images/Elevation/ASIF Apartment  Frazer Town.jpg",
    secondaryImage: "Images/Elevation/ASIF Apartment  Frazer Town.jpg",
    summary: "Tall urban apartment with vertical proportions, planted terraces and warm facade lighting.",
    details: "An urban apartment concept with vertical lines, balanced openings and terrace moments that soften the building mass while keeping construction practical.",
    scope: ["Residential planning", "Facade articulation", "Terrace detailing", "Material palette"]
  },
  {
    slug: "farooq-apartment",
    name: "Farooq Apartment",
    status: "ongoing",
    type: "apartment residential",
    location: "HBR Layout, Bengaluru",
    area: "11,000 sq ft",
    client: "Farooq Apartment",
    image: "Images/Elevation/Farooq Apartment HBR.png",
    secondaryImage: "Images/Farooq Apartment HBR.png",
    summary: "Contemporary apartment block with sculpted balconies, evening lighting and layered frontage.",
    details: "A contemporary apartment elevation using sculpted balconies, lighting and layered edges to give the building a distinct identity within its neighborhood.",
    scope: ["Apartment elevation", "Lighting concept", "Balcony design", "Construction support"]
  },
  {
    slug: "saeed-apartment",
    name: "Saeed Apartment",
    status: "ongoing",
    type: "apartment residential",
    location: "Yasin Nagar, Bengaluru",
    area: "3,500 sq ft",
    client: "Saeed Apartment",
    image: "Images/Elevation/Sayeed Apartment - Yaseen Nagar.png",
    secondaryImage: "Images/Sayeed Apartment - Yaseen Nagar.png",
    summary: "Compact residential apartment designed around efficient planning and a clean elevation.",
    details: "A smaller residential apartment project focused on planning efficiency, simple construction logic and a neat street-facing architectural expression.",
    scope: ["Compact planning", "Elevation design", "Approval drawings", "Site guidance"]
  },
  {
    slug: "n-square-residence",
    name: "N Square Residence",
    status: "completed",
    type: "villa residential",
    location: "HBR Layout, Bengaluru",
    area: "12,800 sq ft",
    client: "Private Client",
    image: "Images/Elevation/Karamath Bellari.png",
    secondaryImage: "Images/Elevation/Ravi Villa.png",
    summary: "Delivered residence with refined material choices, interior detailing and construction oversight.",
    details: "A completed residence with coordinated architecture, interior detailing and material choices carried through site execution.",
    scope: ["Architecture", "Interior detailing", "Material selection", "Construction oversight"]
  },
  {
    slug: "olive-court",
    name: "Olive Court",
    status: "completed",
    type: "apartment residential",
    location: "Hebbal, Bengaluru",
    area: "24,500 sq ft",
    client: "Olive Homes",
    image: "Images/Elevation/Samhitha com.png",
    secondaryImage: "Images/Elevation/Trillium School Arial.png",
    summary: "Completed apartment interiors and common-space coordination for a clean residential experience.",
    details: "A completed residential apartment project with coordinated interior and common-space decisions for a clean, practical living environment.",
    scope: ["Residential interiors", "Common-space coordination", "Finishing guidance", "Handover support"]
  },
  {
    slug: "cedar-house",
    name: "Cedar House",
    status: "completed",
    type: "villa residential",
    location: "Whitefield, Bengaluru",
    area: "9,600 sq ft",
    client: "Khan Family",
    image: "Images/Elevation/Adil KHB.png",
    secondaryImage: "Images/Elevation/Ayaz Khan Street.png",
    summary: "Villa completed with architecture, interior detailing and on-site finishing control.",
    details: "A completed villa with a strong focus on coherent architecture, interior detailing and controlled finishing decisions on site.",
    scope: ["Villa architecture", "Interior detailing", "Finish coordination", "Site execution"]
  },
  {
    slug: "metro-workspace",
    name: "Metro Workspace",
    status: "completed",
    type: "commercial",
    location: "MG Road, Bengaluru",
    area: "16,200 sq ft",
    client: "Metro Build",
    image: "Images/Elevation/Reddy Commercial.png",
    secondaryImage: "Images/Elevation/Moin Airtel - 16.png",
    summary: "Workplace fit-out delivered with planning, material selection and execution coordination.",
    details: "A completed commercial workspace project balancing efficient planning, material selection and coordinated execution for everyday use.",
    scope: ["Workspace planning", "Material selection", "Fit-out coordination", "Execution support"]
  },
  {
    slug: "palm-enclave",
    name: "Palm Enclave",
    status: "completed",
    type: "apartment residential",
    location: "Jayanagar, Bengaluru",
    area: "28,000 sq ft",
    client: "Palm Estates",
    image: "Images/Elevation/Firoz Service.png",
    secondaryImage: "Images/Elevation/zabi hbr night.jpg",
    summary: "Completed residential project integrating approvals, construction and finishing under one team.",
    details: "A delivered residential project shaped by coordinated approvals, construction decisions and finishing support from concept to completion.",
    scope: ["Residential planning", "Approvals coordination", "Construction support", "Finishing guidance"]
  }
];
