import {useEffect,useState} from 'react';
const uid=()=>globalThis.crypto.randomUUID();
export function SearchSelect({label,options,value,onChange,multiple=false}){
 const [query,setQuery]=useState(''),[expanded,setExpanded]=useState(false),[limit,setLimit]=useState(30);
 const selected=multiple?(value||[]):value?[value]:[];
 const matches=options.filter(o=>`${o.label} ${o.value}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="cms-selector"><label>{label}<input type="search" placeholder={`Search or select ${label.toLowerCase()}…`} value={query} onFocus={()=>setExpanded(true)} onChange={e=>{setQuery(e.target.value);setLimit(30);setExpanded(true);}} onKeyDown={e=>{if(e.key==='Escape')setExpanded(false);}}/></label><div className="cms-selections">{selected.map(v=><button type="button" key={v} onClick={()=>onChange(multiple?selected.filter(x=>x!==v):'')} aria-label={`Remove ${options.find(o=>o.value===v)?.label||v}`}>{options.find(o=>o.value===v)?.label||v} ×</button>)}</div>{expanded&&<div className="cms-options"><button type="button" onClick={()=>setExpanded(false)}>Close choices</button>{matches.slice(0,limit).map(o=><button type="button" key={o.value} aria-pressed={selected.includes(o.value)} onClick={()=>{onChange(multiple?selected.includes(o.value)?selected.filter(v=>v!==o.value):[...selected,o.value]:o.value);if(!multiple)setExpanded(false);}}>{o.image&&<img src={o.image} alt="" loading="lazy"/>}<span>{o.label}</span>{selected.includes(o.value)?' ✓':''}</button>)}{!matches.length&&<p>No matching records.</p>}{matches.length>limit&&<button type="button" onClick={()=>setLimit(limit+30)}>Show more</button>}</div>}</div>;
}
function Input({label,value,onChange,type='text'}){return <label>{label}<input type={type} value={value??''} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)}/></label>;}
function Toggle({label,value,onChange}){return <label className="cms-toggle"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
function Order({index,items,onChange}){const move=delta=>{const next=[...items];[next[index],next[index+delta]]=[next[index+delta],next[index]];onChange(next);};return <div className="cms-order"><button type="button" disabled={!index} onClick={()=>move(-1)} aria-label="Move up">↑ Up</button><button type="button" disabled={index===items.length-1} onClick={()=>move(1)} aria-label="Move down">↓ Down</button><button type="button" onClick={()=>onChange(items.filter((_,i)=>i!==index))}>Remove</button></div>;}
export function ProjectFields({project,tags,onChange}){return <div className="website-editor"><Toggle label="Published" value={project.published} onChange={v=>onChange('published',v)}/><Toggle label="Eligible for presentation" value={project.presentationEligible!==false} onChange={v=>onChange('presentationEligible',v)}/><SearchSelect label="Tags" multiple options={(tags||[]).map(t=>({value:t.id,label:t.name}))} value={project.tagIds} onChange={v=>onChange('tagIds',v)}/></div>;}
export function ImagePicker({label,value,onChange,imageOptions}){return <SearchSelect label={label} value={value} onChange={onChange} options={imageOptions.map(i=>({value:i.url,label:i.label||i.name||i.url,image:i.url}))}/>;}
export function ImageListPicker({label,values=[],onChange,imageOptions}){return <SearchSelect label={label} multiple value={values} onChange={onChange} options={imageOptions.map(i=>({value:i.url,label:i.label||i.name||i.url,image:i.url}))}/>;}
export default function WebsiteEditor({content,onChange,images,initialSection='Home'}){
 const [section,setSection]=useState(initialSection),[search,setSearch]=useState('');
 useEffect(()=>setSection(initialSection),[initialSection]);
 const update=(key,value)=>onChange({...content,[key]:value});
 const home=content.home||{slides:[],introduction:''},p=content.presentation||{};
 const imageOptions=images.filter(i=>!content.media?.some(m=>m.url===i.url&&(m.private||m.published===false)));

 return <section className="website-editor"><nav aria-label="Website settings">{['Home','Tags','Associates','Staff','Presentation','Media visibility'].map(s=><button type="button" key={s} aria-pressed={s===section} onClick={()=>{setSection(s);setSearch('');}}>{s}</button>)}</nav><h2>{section}</h2><p>Use Save Changes above to persist your edits.</p>
 {section==='Home'&&<><label>Firm introduction<textarea value={home.introduction} onChange={e=>update('home',{...home,introduction:e.target.value})}/></label><h3>Hero slides</h3><p>Select library images below. New uploads are available through Media / Images.</p><Slides imageOptions={imageOptions} items={home.slides} onChange={slides=>update('home',{...home,slides})}/></>}
 {section==='Tags'&&<><button onClick={()=>update('tags',[...content.tags,{id:uid(),name:'New tag'}])}>Add tag</button>{content.tags.map((t,i)=><article key={t.id}><Input label="Tag name" value={t.name} onChange={name=>update('tags',content.tags.map(x=>x.id===t.id?{...x,name}:x))}/><button onClick={()=>onChange({...content,tags:content.tags.filter(x=>x.id!==t.id),projects:content.projects.map(p=>({...p,tagIds:p.tagIds.filter(id=>id!==t.id)}))})}>Remove tag</button></article>)}</>}
 {['Associates','Staff'].includes(section)&&<PeopleManager title={section} items={content[section.toLowerCase()]||[]} imageOptions={imageOptions} onChange={items=>update(section.toLowerCase(),items)}/>}
 {section==='Presentation'&&<><Toggle label="Enable presentation" value={p.enabled} onChange={enabled=>update('presentation',{...p,enabled})}/><label>Source<select value={p.source} onChange={e=>update('presentation',{...p,source:e.target.value})}><option value="all">All eligible project images</option><option value="projects">Selected projects</option><option value="images">Selected images in custom order</option></select></label>{p.source==='projects'&&<SearchSelect label="Projects" multiple value={p.projectIds} onChange={projectIds=>update('presentation',{...p,projectIds})} options={content.projects.filter(x=>x.published!==false).map(x=>({value:x.slug,label:x.name,image:x.image}))}/>} {p.source==='images'&&<Slides imageOptions={imageOptions} items={p.images||[]} onChange={images=>update('presentation',{...p,images})}/>}<Input label="Seconds per slide (2–120)" type="number" value={p.duration} onChange={duration=>update('presentation',{...p,duration})}/><Input label="Transition seconds" type="number" value={p.transition} onChange={transition=>update('presentation',{...p,transition})}/><label>Image fit<select value={p.fit} onChange={e=>update('presentation',{...p,fit:e.target.value})}><option value="contain">Fit entire image</option><option value="cover">Fill screen</option></select></label><p>Unlisted display URL: /presentation. Only use content approved for public display.</p></>}
 {section==='Media visibility'&&<><Input label="Search media" value={search} onChange={setSearch}/>{images.filter(i=>`${i.label} ${i.url}`.toLowerCase().includes(search.toLowerCase())).slice(0,60).map(i=>{const m=content.media.find(m=>m.url===i.url)||{id:i.url,url:i.url,name:i.label};const edit=(key,value)=>update('media',[...content.media.filter(x=>x.url!==i.url),{...m,[key]:value}]);return <article key={i.url}><h3>{i.label}</h3><Toggle label="Published / public media" value={m.published!==false&&!m.private} onChange={v=>update('media',[...content.media.filter(x=>x.url!==i.url),{...m,published:v,private:!v}])}/><Toggle label="Eligible for presentation" value={m.presentationEligible!==false} onChange={v=>edit('presentationEligible',v)}/></article>;})}<p>Search to narrow the library; up to 60 matching records shown.</p></>}
 </section>;
}

function Slides({items,onChange,imageOptions}){return <><button type="button" onClick={()=>onChange([...items,{id:uid(),image:'',alt:''}])}>Add image</button>{items.map((s,index)=><article key={s.id||index}><h3>Image {index+1}</h3><ImagePicker label="Image" value={s.image} imageOptions={imageOptions} onChange={v=>onChange(items.map((x,i)=>i===index?{...x,image:v}:x))}/><Input label="Alt text" value={s.alt} onChange={v=>onChange(items.map((x,i)=>i===index?{...x,alt:v}:x))}/><Order index={index} items={items} onChange={onChange}/></article>)}</>;}

function PeopleManager({title,items,imageOptions,onChange}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(null),[editing,setEditing]=useState(false);
 const isAssociate=title==='Associates'; const filtered=items.map((person,index)=>({...person,index})).filter(person=>`${person.name} ${person.role} ${person.category||''}`.toLowerCase().includes(query.toLowerCase()));
 const person=selected===null?null:items[selected];
 const update=(field,value)=>onChange(items.map((item,index)=>index===selected?{...item,[field]:value}:item));
 const add=()=>{onChange([...items,{id:uid(),name:'',role:'',bio:'',image:'',published:false}]);setSelected(items.length);setEditing(true);};
 return <><div className="cms-manager-head"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}…`}/><button type="button" onClick={add}>Add {isAssociate?'associate':'staff member'}</button></div><div className="cms-table-wrap"><table className="cms-table"><thead><tr><th>Photo</th><th>Name</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id||item.index}><td>{item.image?<img src={item.image} alt=""/>:<span className="cms-avatar">⌾</span>}</td><td>{item.name||'Untitled'}</td><td>{item.role||'—'}</td><td>{item.published?'Published':'Draft'}</td><td><button type="button" aria-label={`View ${item.name||'person'}`} onClick={()=>{setSelected(item.index);setEditing(false);}}>View</button><button type="button" aria-label={`Edit ${item.name||'person'}`} onClick={()=>{setSelected(item.index);setEditing(true);}}>Edit</button></td></tr>)}{!filtered.length&&<tr><td colSpan="5">No matching records.</td></tr>}</tbody></table></div>{person&&<article className="cms-record-panel"><div className="cms-record-top"><h3>{editing?`Edit ${person.name||'person'}`:person.name||'Person details'}</h3><button type="button" onClick={()=>setSelected(null)}>Close</button></div>{editing?<><Input label="Name" value={person.name} onChange={v=>update('name',v)}/><Input label="Designation / role" value={person.role} onChange={v=>update('role',v)}/><ImagePicker label="Photograph" value={person.image} imageOptions={imageOptions} onChange={v=>update('image',v)}/><label>Biography<textarea value={person.bio||''} onChange={e=>update('bio',e.target.value)}/></label>{isAssociate&&<><Input label="Association category" value={person.category} onChange={v=>update('category',v)}/><Input label="External website" value={person.link} onChange={v=>update('link',v)}/><Input label="Public contact information" value={person.contact} onChange={v=>update('contact',v)}/></>}<Toggle label="Published" value={person.published} onChange={v=>update('published',v)}/><Order index={selected} items={items} onChange={next=>{onChange(next);setSelected(next.findIndex(item=>item.id===person.id));}}/></>:<><p><b>Role:</b> {person.role||'—'}</p><p><b>Category:</b> {person.category||'—'}</p><p>{person.bio||'No biography added.'}</p><button type="button" onClick={()=>setEditing(true)}>Edit details</button></>}</article>}</>;
}
