import Head from 'next/head';
import Script from 'next/script';

export default function Page(){
  return (
    <>
      <Head>
        <title>Journal Details — Nsquare Ventures</title>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <style>{`
@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500&family=Inter:wght@400;500;600&display=swap');
:root{--paper:#f8f7f2;--ink:#17352f;--text:#44514c;--muted:#738078;--line:#d9ddd7;--g:clamp(44px,calc(5vw + 20px),112px);--serif:"Cormorant Garamond",Georgia,serif;--sans:Inter,Arial,sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px var(--sans)}a{color:inherit;text-decoration:none}img{display:block;width:100%}.eyebrow{font-size:10px;letter-spacing:.28em;text-transform:uppercase;color:var(--muted)}
.article-hero{display:grid;grid-template-columns:minmax(0,1fr) minmax(420px,48%);min-height:650px;border-bottom:1px solid var(--line);background:radial-gradient(circle at 0 0,#fff 0,#fbfaf6 42%,#f0eee8 100%);overflow:hidden}
.article-copy{padding:72px clamp(34px,5vw,86px) 64px var(--g);display:flex;flex-direction:column;justify-content:center}.article-overline{display:flex;align-items:center;gap:18px;flex-wrap:wrap;font-size:10px;letter-spacing:.28em;text-transform:uppercase;color:var(--muted)}.article-overline span:first-child{color:var(--ink)}.article-overline:after{content:"";width:92px;height:1px;background:var(--line)}.article-copy h1{font:500 clamp(58px,6.2vw,108px)/.84 var(--serif);letter-spacing:-.045em;margin:30px 0 26px;max-width:800px}.article-copy p{max-width:610px;color:var(--text);font-size:18px;line-height:1.65;margin:0}.article-actions{display:flex;gap:16px;flex-wrap:wrap;margin-top:34px}.article-actions a{border:1px solid var(--line);padding:14px 18px;display:inline-flex;gap:22px;align-items:center;font-size:12px;color:var(--ink);background:rgba(248,247,242,.55)}
.article-image{min-height:650px;background:#e5e8e1;padding:clamp(24px,3vw,44px);display:grid;place-items:center}.article-image img{width:100%;height:100%;max-height:580px;object-fit:cover;filter:saturate(.86) contrast(.96);box-shadow:0 30px 80px rgba(23,53,47,.16)}
.article-body{display:grid;grid-template-columns:minmax(210px,280px) minmax(0,820px);gap:clamp(42px,7vw,118px);padding:82px var(--g) 104px;background:#fbfaf6}.article-body aside{position:sticky;top:104px;align-self:start}.article-side-card{border-top:1px solid var(--ink);border-bottom:1px solid var(--line);padding:18px 0 22px}.article-side-card strong{display:block;font:500 32px/1 var(--serif);margin:22px 0 12px}.article-side-card span{font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:var(--muted)}.article-body aside a{display:inline-flex;gap:18px;margin-top:28px;border-bottom:1px solid var(--line);padding-bottom:10px;color:var(--text);font-size:13px}.article-body article{font-size:19px;line-height:1.86;color:var(--text)}.article-body article>p{margin:0 0 30px}.article-summary{font:500 clamp(30px,3vw,48px)/1.08 var(--serif);letter-spacing:-.02em;color:var(--ink);padding-bottom:34px;border-bottom:1px solid var(--line)}
.article-takeaways{margin:44px 0;padding:32px;background:#f1f0eb;border:1px solid var(--line)}.article-takeaways ul{display:grid;gap:0;margin:20px 0 0;padding:0;list-style:none}.article-takeaways li{display:grid;grid-template-columns:54px 1fr;gap:22px;border-top:1px solid #cfd5ce;padding:18px 0}.article-takeaways li:first-child{border-top:0}.article-takeaways li span{font:500 28px var(--serif);color:var(--ink)}.article-takeaways li p{margin:0;line-height:1.55}.article-wide-image{margin:48px 0;background:#e5e8e1;padding:18px}.article-wide-image img{height:auto;max-height:560px;object-fit:cover;background:#e4e8e4}.article-wide-image figcaption{font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:var(--muted);margin-top:12px}.article-empty{padding:80px var(--g);min-height:420px}
@media(max-width:900px){.article-hero,.article-body{grid-template-columns:1fr}.article-image{min-height:0}.article-body{gap:34px}.article-body aside{position:static}.article-image img{max-height:none}}
@media(max-width:560px){:root{--g:24px}.article-copy{padding-top:48px;padding-bottom:44px}.article-copy h1{font-size:48px}.article-copy p{font-size:16px}.article-image{padding:20px}.article-body{padding-top:54px}.article-body article{font-size:16px}.article-takeaways{padding:22px}.article-takeaways li{grid-template-columns:1fr;gap:8px}}
`}</style>
        <link rel="stylesheet" href="/shared-system.css" />
      </Head>
      <div dangerouslySetInnerHTML={{ __html: `
<header class="header"><a class="brand" href="/"><span class="mark">N</span><span>NSQUARE<small>VENTURES</small></span></a><nav class="nav" aria-label="Primary"><a href="/">Home</a><a href="/projects">Projects</a><a href="/expertise">Expertise</a><a class="active" href="/journal">Journal</a><a href="/contact">Contact</a></nav><div class="head-actions"><a class="inquire" href="/contact">Inquire <span>→</span></a><button class="menu-dot site-menu-trigger" type="button" aria-label="Open navigation">≡</button></div></header>
<main id="journalDetail"><section class="article-empty"><div class="eyebrow">Journal</div><h1>Loading article.</h1></section></main>
<footer class="footer site-footer" id="footer"><div class="footer-main site-footer-grid"><div class="site-footer-brand"><a class="brand" href="/"><span class="mark">N</span><span>NSQUARE<small>VENTURES</small></span></a><p>Architecture-led design and delivery<br>in Bengaluru.</p></div><nav class="footer-links site-footer-col" aria-label="Footer explore"><h2>Explore</h2><a href="/projects">Projects</a><a href="/expertise">Expertise</a><a href="/journal">Journal</a><a href="/contact">Contact</a></nav><div class="site-footer-col"><h2>Practice</h2><a href="/expertise">Architecture</a><a href="/expertise">Interiors</a><a href="/expertise">Construction</a><a href="/expertise#elevation">Approvals &amp; Coordination</a><a href="/expertise#elevation">Elevation Consultation</a></div><div class="footer-contact site-footer-location"><h2>Based In</h2><strong>Bengaluru<br>Karnataka<br>India</strong><a href="/contact">Start a conversation <span>→</span></a></div></div></footer>
<div class="site-scrim" id="siteScrim"></div><aside class="site-side" id="siteSide" aria-hidden="true"><div class="site-side-top"><a class="brand" href="/"><span class="mark">N</span><span>NSQUARE<small>VENTURES</small></span></a><button class="site-close" id="siteMenuClose" type="button">Close ×</button></div><div class="site-side-label">Menu</div><nav class="site-side-nav"><a href="/">Home <span>01</span></a><a href="/projects">Projects <span>02</span></a><a href="/expertise">Expertise <span>03</span></a><a href="/journal">Journal <span>04</span></a><a href="/contact">Contact <span>05</span></a></nav><div class="site-side-foot"><div>Spaces<br>People<br>Belong in Harmony</div><div class="site-cross" aria-hidden="true"></div></div></aside>


` }} />
      <Script src="/journal-data.js" strategy="afterInteractive" />
      <Script src="/shared-system.js" strategy="afterInteractive" />
    </>
  );
}
