const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
const base='http://localhost:3001',headers={'x-cms-password':process.env.TEST_CMS_PASSWORD||'admin123','content-type':'application/json'};
const read=async()=>{const r=await fetch(base+'/api/content',{headers});assert.equal(r.status,200);return r.json();};
(async()=>{const original=await read();const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:1400,height:900}});await page.goto(base+'/admin');await page.getByLabel('Password',{exact:true}).fill(headers['x-cms-password']);await page.getByRole('button',{name:'Open CMS',exact:true}).click();await page.getByText(/Loaded \d+ projects/).waitFor();
 const save=async()=>{await page.getByRole('button',{name:'Save Changes',exact:true}).click();await page.getByText('Saved. Refresh the public site to see updates.').waitFor();};
 await page.getByRole('button',{name:'Website',exact:true}).click();await page.getByRole('button',{name:'Add image',exact:true}).click();const slide=page.locator('.website-editor article').last();await slide.getByPlaceholder('Search or select image…').fill('Samhitha com');await slide.locator('.cms-options button').filter({hasText:'Samhitha com'}).first().click();await slide.getByLabel('Alt text',{exact:true}).fill('Temporary validation slide');await save();assert.equal((await read()).home.slides.at(-1).alt,'Temporary validation slide');console.log('Searchable image selection and slide creation saved');
 await page.getByRole('button',{name:/^Works/}).first().click();await page.getByPlaceholder('Search or select tags…').fill('Residential');await page.locator('.cms-options button').filter({hasText:'Residential'}).click();await page.getByPlaceholder('Search or select tags…').fill('Commercial');await page.locator('.cms-options button').filter({hasText:'Commercial'}).click();await save();assert((await read()).projects[0].tagIds.length>=2);console.log('Project multiple-tag selector saved');
 await page.getByRole('button',{name:'Website',exact:true}).click();await page.getByRole('button',{name:'Staff',exact:true}).click();await page.getByRole('button',{name:'Add staff member',exact:true}).click();const staff=page.locator('.website-editor article').last();await staff.getByLabel('Name',{exact:true}).fill('Temporary validation record');await staff.getByLabel('Designation / role',{exact:true}).fill('Test fixture');await staff.getByRole('button',{name:'Move up',exact:true}).click();await save();assert.equal((await read()).staff[0].name,'Temporary validation record');await page.reload();await page.getByText(/Loaded \d+ projects/).waitFor();await page.getByRole('button',{name:'Website',exact:true}).click();await page.getByRole('button',{name:'Staff',exact:true}).click();assert.equal(await page.getByLabel('Name',{exact:true}).first().inputValue(),'Temporary validation record');console.log('Separate staff editing and order persist after browser reload');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/');await page.getByRole('button',{name:'Open navigation',exact:true}).click();assert.deepEqual(await page.locator('.site-side-nav a').allTextContents(),['Works 01','Office 02','Contact 03']);await page.keyboard.press('Escape');assert.equal(await page.locator('.site-side').getAttribute('aria-hidden'),'true');console.log('Mobile menu and Escape verified');
 await page.goto(base+'/contact');await page.getByRole('button',{name:'Send on WhatsApp'}).click();assert.equal(await page.locator('#name').evaluate(el=>el.validity.valueMissing),true);console.log('Contact required-field validation verified');
 const redirect=await fetch(base+'/projects.html',{redirect:'manual'});assert.equal(redirect.status,308);assert.equal(await page.locator('a[href="/presentation"]').count(),0);console.log('Legacy redirect and no presentation link verified');
 const unauthorized=await fetch(base+'/api/content',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(unauthorized.status,401);console.log('Unauthorized write rejected');
}finally{const r=await fetch(base+'/api/content',{method:'POST',headers,body:JSON.stringify(original)});assert.equal(r.status,200);await browser.close();console.log('Original content restored');}})().catch(e=>{console.error(e);process.exitCode=1;});
